kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: container-kill-experiment
  namespace: squidgame
spec:
  schedule: '@every 15s'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - squidgame
      labelSelectors:
        app: kafka-strimzi-api
    mode: one
    containerNames:
      - kafka-strimzi-producer
    action: container-kill
    duration: 5m
    gracePeriod: 0