apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-strimzi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-strimzi
  template:
    metadata:
      labels:
        app: kafka-strimzi
    spec:
      containers:
      - name: kafka-strimzi-producer
        image: kafka-api
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 30
        env:
        - name: kafkaURL
          value: "my-cluster-kafka-bootstrap:9092"
        - name: topic
          value: "squidgame"
        - name: GroupID
          value: "squidgame"
      - name: kafka-strimzi-worker
        image: kafka-worker
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 30
        env:
        - name: kafkaURL
          value: "my-cluster-kafka-bootstrap:9092"
        - name: topic
          value: "squidgame"
        - name: GroupID
          value: "squidgame"
        - name: redisURL
          value: "35.225.83.23:6379"
        - name: redisPassword
          value: "password85@"
---
apiVersion: v1
kind: Service
metadata:
  name: np-kafka-strimzi
spec:
  type: NodePort
  selector:
    app: kafka-strimzi
  ports:
  - port: 8080
    targetPort: 8080

