kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: delay
  namespace: squidgame
spec:
  selector:
    namespaces:
      - squidgame
    labelSelectors:
      app: kafka-strimzi-api
  mode: one
  action: delay
  delay:
    latency: 500ms
    correlation: '100'
    jitter: 0ms
  direction: to
