kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: pod-failure-experiment
  namespace: chaos-testing
spec:
  schedule: '@every 15s'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - squidgame
      labelSelectors:
        app: kafka-strimzi-api
    mode: one
    action: pod-failure
    duration: 5m
    gracePeriod: 0