apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: react-app
  template:
    metadata:
      labels:
        role: react-app
    spec:
      containers:
      - name: react-app
        image: docker.io/cristianfrancisco85/react-app-so1:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: np-react-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    role: react-app
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ig-react-app
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: np-react-app
            port:
              number: 80