FROM golang:1.15-alpine
LABEL maintainer="Cristian Meoño <cristianfrancisco85@gmail.com>"
WORKDIR /app
COPY . .
RUN go mod download
RUN cd worker && go build && cd ..
RUN export GOOGLE_APPLICATION_CREDENTIALS=./gRPC-Server/GCPKey.json
EXPOSE 8080
CMD ["./worker/worker"]